<?php
/*  
    For Miguel A. Tunubalá.
    www.margunsoft.com
    2019, Popayán
*/
    
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Administrador_tablas extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login(); // Verifica login de usuario
        // echo (is_login());
        $this->load->model('Persona_model');
        $this->load->library('form_validation');        
		$this->load->library('datatables');
    }

    public function index()
    {
    	// $sql = $this->db->query('SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE  =""');
    	$this->db->select('*');
		$this->db->from('INFORMATION_SCHEMA.TABLES');
		$this->db->where('TABLE_SCHEMA','prosalud_v1_margunsoft');
		$resulset = $this->db->get();
		$data['tables'] = $resulset->result_array();



        $data['page'] = 'Adminitrar';
        $data['module']='Selector de tablas';
        $data['_view'] = 'administrador_tablas/vistas';
        $this->load->view('layouts/main',$data);
    } 
    
    

}

/* End of file Persona.php */
/* Location: ./application/controllers/Persona.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-08 03:46:44 */
/* http://harviacode.com 
// $password = $this->input->post('Contrasena_Usu',TRUE);
// $hashPassword   = password_hash($password,PASSWORD_BCRYPT,array("cost"=>4));
            
*/