<?php
/*  
    For Miguel A. Tunubalá.
    www.margunsoft.com
    2019, Popayán
*/
    
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Table extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login(); // Verifica login de usuario
        $this->load->library('form_validation');
        $this->load->model('Funciones_model');
        $this->load->model('Datatable_model'); 
    }

    public function index()
    {
        redirect();
    }
    public function get_documents($type='', $Id_Per='')
    {
        switch ($type) {
            case 'income':
                // Ingresos
                $name = "venta";
                $Id_DocTip = 1;
                break;
            case 'expenses':
                // egresos
                $name = "compra";
                $Id_DocTip = 2;
                break;
            case 'quotes':
                // cotizaciones
                $name = "compra";
                $Id_DocTip = 6;
                break;
            case 'referrals':
                // remisiones
                $name = "remisión";
                $Id_DocTip = 5;
                break;
            case 'purchase_order':
                // orden de compra
                $name = "compra";
                $Id_DocTip = 7;
                break;
            default:
                redirect();
                break;
        }
        $where = array(
            array('field'=>'Id_Per', 'value'=>$Id_Per),
            array('field'=>'Id_DocTip', 'value'=>$Id_DocTip),
            array('field'=>'Id_DocEst IN', 'value'=>array(1,6))
            // array('field'=>'OR Id_DocEst-', 'value'=>6)
        );
        $columns = 'Id_Doc, Contacto, Identificacion_Per, Id_Per, FechaRegistro_Doc, Numero_Doc, FechaDocumento_Doc, FechaVencimiento_Doc, IvaIncluido_Doc, Usuario_Usu, Nombre_DocTip, Nombre_DocEst, Nombre_TerPag, Dias_TerPag';
        $result = $this->Datatable_model->start_datatable($columns, 'vw_documento', $totalData, $totalFiltered, $where); // Iniciar datatable
        $data = array();
        if(!empty($result))
        {
            foreach ($result as $c => $rs) {
                unset($row);
                $total_documento = $this->Funciones_model->get_totalKardex_by_document($rs->Id_Doc);
                $row['Id_Doc'] = $rs->Id_Doc;
                $row['Id_Per'] = '('.$rs->Identificacion_Per.') '.$rs->Contacto;
                $row['Identificacion_Per'] = $rs->Identificacion_Per;
                $row['FechaRegistro_Doc'] = $rs->FechaRegistro_Doc;
                $row['Numero_Doc'] = $rs->Numero_Doc;
                $row['FechaDocumento_Doc'] = $rs->FechaDocumento_Doc;
                $row['FechaVencimiento_Doc'] = $rs->FechaVencimiento_Doc;
                $row['IvaIncluido_Doc'] = $rs->IvaIncluido_Doc;
                $row['Id_Usu'] = $rs->Usuario_Usu;
                $row['Id_DocTip'] = $rs->Nombre_DocTip;
                $row['Id_DocEst'] = $rs->Nombre_DocEst;
                $row['Id_TerPag'] = $rs->Nombre_TerPag;
                $row['total_doc'] = number_format($total_documento,2);
                $row['opciones'] = '<button class="btn btn-warning" onclick="add_DetailDoc('.$rs->Id_Doc.', \''.$rs->Numero_Doc.'\', \''.$total_documento.'\')"><i class="fas fa-plus"></i></button>';
                $data[$c] = $row;
            }
        }
        $this->Datatable_model->output_datatable($totalData, $totalFiltered, $data);

    }
    

}

/* End of file Categoria_item.php */
/* Location: ./application/controllers/Categoria_item.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-24 01:25:57 */
/* http://harviacode.com 
// $password = $this->input->post('Contrasena_Usu',TRUE);
// $hashPassword   = password_hash($password,PASSWORD_BCRYPT,array("cost"=>4));
            
*/