FROM mysql:5.7.8

# Copia un archivo de configuración personalizado (si es necesario)
COPY database/SQL/margunsoft_financia_v2.sql /docker-entrypoint-initdb.d/

# Expone el puerto de MySQL (por defecto: 3306)
EXPOSE 3306